import Router from '@koa/router';
import add from './add';
import del from './del';
import getlist from './getlist';
import login from './login';
import register from './register';
import sendcode from './sendcode';
const route = new Router();
route.post('/login', login);
route.get('/getlist', getlist);
route.post('/add', add);
route.post('/del', del);
route.post('/sendcode', sendcode);
route.post('/register', register);
export default route;
